### ISSUE TITLE
Subptool doesn't support russian launguage

### ISSUE THREAD

**Issue by eHerbaciarz** [Atvaark/FoxEngine.TranslationTool#10]
Hi, 

I want try to use Russian lauguage like as base to translation.

When I unpacked russian font - I see cyrllic chars - that works fine.

But when I unpack files *.subp - I see question marks in the place of cyrllic chars.

I guess the problem is in Subptool which use only Basic Latin Chars (But I'm not sure).
I tried to replace questions marks with cyrlic chars in subp files and repack this. But game doesn't recognize this chars. 

Is it possible to fix that? Or i did something wrong?

**Comment by Atvaark** [comment]
Did you read the README of SubpTool? Which encoding did _you_ specify when unpacking/packing the subtitles?
