### ISSUE TITLE
Text question marks.

### ISSUE THREAD

**Issue by taolovemessi** [Atvaark/FoxEngine.TranslationTool#11]
I traslate file EngText/s10010.subp  to thai sub. I repacked and unpacked to view text but text is ?????

**Comment by Atvaark** [comment]
You'd have to translate one of the UTF-8 language (japanese or portuguese) subs as you can't encode thai in ISO-8859.
You'll also have to import a thai font into the game which isn't trivial.

**Comment by taolovemessi** [comment]
Yes i fix it but i need font thai.ffnt. How to build font TT

**Comment by Atvaark** [comment]
Unpack the japanese font and try to understand the format. If you figured it out you can just create your own font and repack it.

I won't offer you any support with it though.
