### ISSUE TITLE
Requsting modification of SubpTool

### ISSUE THREAD

**Issue by abuali129** [Atvaark/FoxEngine.TranslationTool#14]
Hi,
As I used the SubpTool.exe for long time know, every issues I encounter with wrong editing format is highlighted by the SubpTool except for one.
That is when these two Line  _**<Line Text and <Timing Start**_  has swap positions.

While Editing There's a chance that the order of these two lines will be changed by mistake. Then when encoding the xml to subp it show that there's an error but it's not  highlighting which Line number is causing the fault.

That is what it showed
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at SubpTool.Subp.SubpEntry.Write(Stream outputStream, Encoding encoding)
   at SubpTool.Subp.SubpFile.Write(Stream outputStream, Encoding encoding)
   at SubpTool.Program.PackSubp(String path, Encoding encoding)
   at SubpTool.Program.Main(String[] args)

```

**Comment by Atvaark** [comment]
You'd have to provide the file that caused that error.

**Comment by abuali129** [comment]
https://mega.nz/#!uZtFCJhA!TmDTL5YtB8gO0o8ZhZN36wru0akbuLU1ajKPVt3BnR0

**Comment by Atvaark** [comment]
Invalid Subp XML-files will now crash in [v0.2.5.](https://github.com/Atvaark/FoxEngine.TranslationTool/releases/tag/v0.2.5) and the error message will contain the line and position of the issue.

**Comment by abuali129** [comment]
Thanks
