### ISSUE TITLE
There are missing Lines and Texts in subp.xmls!!

### ISSUE THREAD

**Issue by SLaYeR983** [Atvaark/FoxEngine.TranslationTool#17]
Hi atvaark... I can't proper running to SubpTool(for MGSV)

Some strings half or nothing extracted from the subp files to .xmls. I guess because of these are not linked some time codes as originally, maybe... but these strings shows in the game with original files...

Exam1: 10010.subp file

3227886550 | [C=21]Nine years ago, you were injured -
3227886550 | in an explosion.
3227886550 | Upon examination, we discovered 100 and  8 foreign bodies embedded within you.

it' s OK but...

2142450332 | Nine years ago, you were injured - $in an explosion. $Upon examination, we discovered 100 and 8 foreign bodies embedded within you.

While it should be like this but it shows as empty in 10010.xml

Exam2: 10020.subp

3058488293 | The villagers fled the war and evacuated a while back.$Since then, it's become a base for the Soviet's 40th Army.
While it should be like this and so it is in not modded the .subp file and the game (without $) but just shows that sentence "The villagers fled the war and evacuated a while back." and no rest in the modded game and 10020.xml.

Can you fix that problem? because this problem exists in hundreds of lines... missing or all nothing.

**Comment by abuali129** [comment]
Here is the original collection of xml files that I extracted 3 years ago
https://mega.nz/file/HBUBhKxD#3vP69x9hyC6txU16UbBEep38C_UMB4UB2T6gVZYhqq4
May be the tool need to be updated to support the latest version, but as I remembered, it worked just fine back then...
And even I managed to fan translated it and created a mod for it

https://www.nexusmods.com/metalgearsolidvtpp/mods/596?tab=description

**Comment by Atvaark** [comment]
There are plenty of TODOs left to fix in the .subp file support. One of them was an issue where there are different amounts of lines and timing information.

I tried fixing this issue but can't test if the fix works as expected.
[Release v0.2.6](https://github.com/Atvaark/FoxEngine.TranslationTool/releases/tag/v0.2.6)

**Comment by SLaYeR983** [comment]
Thanks for helps guys... I will try these ones too.

**Edit:** There is no problem for now.
