### ISSUE TITLE
Support X360/PS3

### ISSUE THREAD

**Issue by michalss** [Atvaark/FoxEngine.TranslationTool#3]
Hello,

Can you please make support for X360/PS3, big endian..

Thx

**Comment by michalss** [comment]
for files subp :( no support big endian

**Comment by Atvaark** [comment]
I don't have the spare time to support them at the moment. You could always just fork this repository and try it yourself. Classes to work with big endian can be found [here](https://github.com/Atvaark/FoxEngine.TranslationTool/tree/master/LangTool/Utility).

**Comment by eHerbaciarz** [comment]
https://github.com/JakubDziworski/FoxEngine.TranslationTool/releases - LangToolPS3 Support for GZ

https://www.dropbox.com/sh/f6g96u5feclpidi/AABBC-hph6-iiy3SKC0iEEWVa?dl=0 -Fnttool, Subbtool PS3 Support (and another tools for PS3).
