### ISSUE TITLE
Missing parameter for lng2 format

### ISSUE THREAD

**Issue by al6uiz** [Atvaark/FoxEngine.TranslationTool#4]
Hi, 
I fonund some missing parameter for lang format.
An entity header constant '1' is not only value.
e.g.) tpp_announce_log.eng has '5', '6' for header value.

I think, it's kind of some highlighting parameter.
Originally,  message  [Map information updated.] is shown with yellow color.
but, after I update lang file, it just shown white color.

Thanks.

**Comment by Atvaark** [comment]
Good find.
With [v0.2.3](https://github.com/Atvaark/FoxEngine.TranslationTool/releases/tag/v0.2.3) the value will get saved in the _Color_ attribute. See if the the _"Map Info Updated"_ line gets displayed correctly now.

I didn't check what each individual code does. This is the distribution of the codes if anyone wonders.

| Code | Count |
| --- | --- |
| 1 | 136968 |
| 5 | 12432 |
| 6 | 1936 |
| 7 | 144 |
| 8 | 32 |
| 513 | 24 |

**Comment by Atvaark** [comment]
Any news on this? I'll close this issue otherwise.
