### ISSUE TITLE
Some issues for FfntTool

### ISSUE THREAD

**Issue by al6uiz** [Atvaark/FoxEngine.TranslationTool#5]
1. Glyphs in XML files should be sorted by (char) value.
   I found this restriction when I add new glyphs for translating japanese to korean.
   I think you need to remark this.
2. A value of VerticalShift can be negative number. (byte -> sbyte)
3. You would already know, size of font bitmap can be bigger than 1024x512.(1024 x 1024 works well on TPP)

**Comment by Atvaark** [comment]
In the original ffnt files only VerticalShift values between 0 and 54 are used. Are you sure about 2?
I mean does the game interpret negative values correctly?

**Comment by al6uiz** [comment]
![2015-10-23_00004](https://cloud.githubusercontent.com/assets/12061743/10690412/a2f714a2-79bc-11e5-926d-03297a666909.gif)

Here's screenshot :)

**Comment by Atvaark** [comment]
Thanks,

makes me wonder which other attributes support negative values.

Can you elaborate your 3rd issue some more? Do 1024 x 1024 fonts get displayed incorrectly or do they just fail to load?
Although this might have something to do with the unknown values in the GlyphMap header.

**Comment by al6uiz** [comment]
No, 3rd issue is just information. I just tell you 1024x1024 size font texture works well.

I think it's useful information for who want to translate TPP into chinese. 

Never mind. Thank you.
