### ISSUE TITLE
RePack *.xml file to *.subp

### ISSUE THREAD

**Issue by eHerbaciarz** [Atvaark/FoxEngine.TranslationTool#7]
Hi, 

I have problem - when I used SubpTool to convert *.subp to *.xml file i always get  UTF-8 (First line of this file is - <?xml version="1.0" encoding="utf-8"?>)

I'm changed in SubpTool.exe.config encoding on ISO-8859-1, but the same problem - always UTF-8.

I guess this is a source of my problem (when i RePack launguage file - the text from this file doesn't appear in game).

**Comment by Atvaark** [comment]
Hey,
the encoding of the generated xml file will always be utf-8. The option you can specify is to read and write subp files with the correct encoding.

Either you are using the wrong language settings in the game or letters that the game can't display.

**Comment by eHerbaciarz** [comment]
But I've checked everything I didn't change anything in *.xml file - just unpacked and repacked.

I recorded video (sorry for no audio but i forgot to enable this when I start record)

https://www.youtube.com/watch?v=WPTYCrFXEoQ&feature=youtu.be

In 6:46 Miller start talking, but sub doesn't appears. (Options is okey, and I did't change anything in Xml file - just open and close it). Where is my fault ?

**Comment by Atvaark** [comment]
1. Changing the XML encoding in the SubpTool.exe.config doesn't do anything. It's the standard XML prolog and just tells applications which encoding should be used to read the SubpTool.exe.config.
2. You are using versions of my tools that target the updated TPP files. Use GzsTool 0.2 and SubpTool 0.1.3 of you want to target GZ files.

**Comment by eHerbaciarz** [comment]
I used SubTool 0.1.3 and works fine! Thank You that was very helpfull!

I have another question i found dialogs subtitles in folder_game\data_02\Assets\tpp\pack\ui\subtitles\EngVoice (and there are fonts/and dialogues to each mission).

But where is launguage files for menu (I cannot find any *.lng file or any file with text of menu/options etc.)?

**Comment by Atvaark** [comment]
I don't have the game installed, so I can't check which files are used for the menus. You could try extracting all g0s, fkp and fpkd files somewhere and searching for common menu strings with any text editor (e. g. _Find in Files_ in Notepad++).
