### ISSUE TITLE
Font file - question marks. 

### ISSUE THREAD

**Issue by eHerbaciarz** [Atvaark/FoxEngine.TranslationTool#8]
Hi, 

I have little issue in MGS Ground Zeroes:
I opened latin font from data_02\Assets\tpp\font\LatinFont by FfntTool (ver. 1.3)
That unpacked xml and pngs files. I checked xml and I saw additional chars like : "ÀÁ ÀÁ Â Ã Ä Å Æ Ç È É Ê Ë Ì Í Î Ï Ð Ñ Ò Ó Ô Õ Ö Ø Ù Ú Û Ü Ý Þ ß à á" (they are also in png) 

But when I will use those chars in subtitles i've got question marks like " ??????????????????????" (I don't change anything in ftnt file)

How resolve this? I need additional chars to translate game to my mother tongue.

Thanks in advance,
ethar

**Comment by Atvaark** [comment]
Looks like you use a different encoding for the subtitles than the game expects. Which languages subtitles did you edit/use ingame. If it's English, then the game probably only supports ASCII (not ANSI).

**Comment by eHerbaciarz** [comment]
Yes, I used english subtitles.

Thanks, but that strange (with those additional chars in xml file).

For example char " is  &quot; in file, I will try use replace chars never used in game - for example &lt;  - < or another chars. I try with this.

Or another way I use russian files as base. (Maybe those files use ANSI) that probaly will resolve problem, when I check that I will let know.

Thanks a lot!

Best regards.
