### ISSUE TITLE
PS3 Support

### ISSUE THREAD

**Issue by szczuru** [Atvaark/FoxEngine.TranslationTool#9]
Hi, i saw issue #3 but maybe something changed in last 6 months? ;) I can unpack every file in PS3's GZ except *.subp files - can you add  support for it?

**Comment by eHerbaciarz** [comment]
It woud be great if Atvaark will add PS3 support.

**Comment by eHerbaciarz** [comment]
https://github.com/JakubDziworski/FoxEngine.TranslationTool/releases - LangToolPS3 Support for GZ

 https://www.dropbox.com/sh/f6g96u5feclpidi/AABBC-hph6-iiy3SKC0iEEWVa?dl=0 -Fnttool, Subbtool PS3 Support (and another tools for PS3).

Topic to close :)
